# vim ft=yaml
# travis-ci.org definition for skimage build
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them

language: erlang

env:
    - PYTHON=python PYSUF='' PYVER=2.7

install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-dev
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-scipy
    - sudo apt-get install $PYTHON-matplotlib
    - sudo apt-get install $PYTHON-setuptools
    - sudo pip-$PYVER install cython
    - sudo pip-$PYVER install scikit-image
    - sudo pip-$PYVER install pytest
    - sudo apt-get install libfreeimage3
    - sudo $PYTHON setup.py build_ext -i 
    - sudo $PYTHON setup.py install

script:
    - py.test
